#!/bin/sh
PROJECTS_PATH=$1
MODEL_NAME=$2
LP_MAJOR=$3
LP_MINOR=$4
PROJECTS_IMAGE_PATH=$PROJECTS_PATH/image
REG=$5
LP_JS=$6
FILE_NAME=$2_$3$4$5
LP_ID=$2_$3.$4_$5_$7

if [ ! -d $PROJECTS_IMAGE_PATH ]
then
	mkdir $PROJECTS_IMAGE_PATH
	chmod 644 $PROJECTS_IMAGE_PATH
fi

rm -f $PROJECTS_IMAGE_PATH/$FILE_NAME
rm -f $PROJECTS_IMAGE_PATH/$FILE_NAME.lng
$PROJECTS_PATH/tools/mksquashfs_ap99 $PROJECTS_PATH/tools/m17n/$LP_JS $PROJECTS_IMAGE_PATH/$FILE_NAME -be
chmod 644 $PROJECTS_IMAGE_PATH/$FILE_NAME
dd if=$PROJECTS_IMAGE_PATH/$FILE_NAME of=$PROJECTS_IMAGE_PATH/$FILE_NAME.lng bs=1k conv=sync
echo -n $LP_ID >> $PROJECTS_IMAGE_PATH/$FILE_NAME.lng
rm -f $PROJECTS_IMAGE_PATH/$FILE_NAME
